"""Initial Migration

Revision ID: 48d038a16d4a
Revises: a7e2442bcf16
Create Date: 2020-05-12 08:11:09.881446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d038a16d4a'
down_revision = 'a7e2442bcf16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscirbe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blogs', sa.Column('posted', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('posted', sa.DateTime(), nullable=True))
    op.alter_column('comments', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('comments', 'posted')
    op.drop_column('blogs', 'posted')
    op.drop_table('subscirbe')
    # ### end Alembic commands ###
