"""Initial Migration

Revision ID: 964836a37202
Revises: 48d038a16d4a
Create Date: 2020-05-12 11:07:53.478609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964836a37202'
down_revision = '48d038a16d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'content',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('blogs', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('blogs', 'content',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
